# Using Numpy Arrays

In [2]:
import numpy as np

In [3]:
# baisc list 
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
# 2D array
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
# Creating arrays of single value, 0
np.zeros(shape=(3,5)) # (rows, columns)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# Creating arrays of single value, 1
np.ones((2,4)) # (height, width)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
# set seed to create same random numbers each time
np.random.seed(101)

In [12]:
arr = np.random.randint(0,100,10) # give me 10 numbers, 0 through 100

In [13]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [14]:
arr2 = np.random.randint(0,100,10)

In [15]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [16]:
# find max
arr.max()

95

In [17]:
# find index of max value
arr.argmax()

0

In [18]:
# find min value
arr.min()

9

In [19]:
# find index of min value
arr.argmin()

7

In [20]:
# find mean 
arr.mean()

60.8

In [21]:
# reshape arrays 
# make sure that shape makes sense; arr has 10 elements
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [22]:
# Index
mat = np.arange(0,100).reshape(10,10)

In [23]:
mat 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
mat.shape

(10, 10)

In [25]:
row = 4 
col = 6

In [26]:
mat[row,col]

46

In [27]:
# Slice to grab all items in column
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [28]:
# Slice to grab all items in row
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
# Grab chunks through slicing in 2D
mat[0:3, 0:3] # returns 3x3, starting with 0 but not including 3

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [30]:
# Reassign numbers 
mat[0:4, 0:3] = 0

In [31]:
mat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [ 0,  0,  0, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
mynewmat = mat.copy()

In [54]:
mynewmat

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mynewmat[0:6,:] = 999

In [56]:
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])